"""
出力フォーマット関連の関数
"""

import re
from typing import Dict, Any, List, Tuple

from cve_analyzer import translate_severity_to_japanese


def format_github_comment(analysis_result: str, pr_number: int, pr_title: str, repo: str = "", cve_info_list: List[Tuple[str, int, str]] = None) -> str:
    """GitHub コメント用にフォーマット

    Args:
        analysis_result: 分析結果
        pr_number: PR番号
        pr_title: PRタイトル
        repo: リポジトリ名（owner/repo形式）
        cve_info_list: [(cve_id, alert_number, alert_url), ...] のリスト
    """

    # タイトル部分の生成
    title = "# セキュリティ分析結果"
    if cve_info_list:
        # Alert番号とURLを取得（重複を除去）
        alert_dict = {}  # {alert_number: alert_url}
        for _, alert_number, alert_url in cve_info_list:
            if alert_number > 0 and alert_url:
                alert_dict[alert_number] = alert_url

        # Alert番号のリンクを作成
        if alert_dict:
            alert_links = [f"[#{num}]({url})" for num, url in sorted(alert_dict.items())]
            title = f"# Dependabot Alert {', '.join(alert_links)} セキュリティ分析結果"

    comment = f"""{title}

**PR**: #{pr_number} - {pr_title}

{analysis_result}

---

*This comment was automatically generated by dependahunt.*
"""
    return comment


def format_cve_info_section(all_vuln_data: List[Dict[str, Any]]) -> str:
    """CVE基本情報セクションをフォーマット"""
    if not all_vuln_data:
        return ""

    result = "## 📋 CVE基本情報\n\n"
    for vuln_info in all_vuln_data:
        severity_jp = translate_severity_to_japanese(vuln_info['severity'])
        result += f"### {vuln_info['id']}\n"
        result += f"**🔗 CVE詳細**: https://nvd.nist.gov/vuln/detail/{vuln_info['id']}\n"
        result += f"**CVSS基準重要度**: {severity_jp}\n"
        result += f"**公開日**: {vuln_info['published'][:10] if vuln_info['published'] != 'Unknown' else '不明'}\n"
        result += f"**説明**: {vuln_info['description'][:200]}{'...' if len(vuln_info['description']) > 200 else ''}\n\n"

    return result
