"""
GitHub API関連の関数
"""

import json
import re
from typing import Dict, Any, List, Tuple

from github import Github
from github.GithubException import GithubException

from version_utils import version_in_range, compare_versions
import markers


def get_pr_details(repo: str, pr_number: int, github_token: str) -> Dict[str, Any]:
    """GitHub APIからPR詳細を取得"""
    g = Github(github_token)
    repository = g.get_repo(repo)
    pr = repository.get_pull(pr_number)

    return {
        'number': pr.number,
        'title': pr.title,
        'body': pr.body or '',
        'state': pr.state,
        'html_url': pr.html_url,
        'user': {'login': pr.user.login} if pr.user else None,
    }


def extract_cve_numbers(pr_body: str) -> List[str]:
    """PR本文からCVE番号を抽出"""
    cve_pattern = r'CVE-\d{4}-\d+'
    cves = re.findall(cve_pattern, pr_body, re.IGNORECASE)
    return list(set(cves))  # 重複を除去

def normalize_package_name(name: str, ecosystem: str) -> str:
    # same as renovate's normalizePackageName
    # https://github.com/renovatebot/renovate/blob/930cf6633ccf38f3578cb112c7ad42c7f99e1cdb/lib/modules/platform/utils/github-alerts.ts
    if ecosystem == "pip":
        return re.sub(r"[-_.]+", "-", name).lower()
    return name

def find_cves_by_package_and_version(
    repo: str,
    package_name: str,
    from_version: str,
    to_version: str,
    github_token: str
) -> List[Tuple[str, int, str]]:
    """パッケージ名とバージョンからこのPRで修正されるCVE番号を取得

    Args:
        repo: リポジトリ名（owner/repo形式）
        package_name: パッケージ名 (例: "lodash")
        from_version: 現在のバージョン (例: "4.17.20")
        to_version: 修正先のバージョン (例: "4.17.21")
        github_token: GitHub トークン

    Returns:
        このPRで修正されるCVE情報のリスト [(cve_id, alert_number, alert_url), ...]
    """
    try:
        print(f"🔍 パッケージ '{package_name}' (v{from_version} → v{to_version}) のCVE番号を検索中...")
        print(f"   リポジトリ: {repo}")

        g = Github(github_token)
        repository = g.get_repo(repo)

        # Dependabotアラートを取得
        alerts = repository.get_dependabot_alerts(state='open')
        matching_cves = []
        for alert in alerts:
            vuln = alert.security_vulnerability
            # パッケージ名でフィルタ
            if normalize_package_name(vuln.package.name, vuln.package.ecosystem) != normalize_package_name(package_name, vuln.package.ecosystem):
                continue
            
            # from_versionが脆弱なバージョンであるかのチェック
            if not version_in_range(from_version, vuln.vulnerable_version_range):
                continue

            # to_versionが修正済みバージョン以上であるかのチェック
            if compare_versions(to_version, vuln.first_patched_version["identifier"]) < 0:
                continue
            
            cve = alert.security_advisory.cve_id
            if not cve:
                continue
            cve_info = (cve, alert.number, alert.html_url)
            matching_cves.append(cve_info)

        print(f"   ✅ {len(matching_cves)} 件のアラートを取得")

        if matching_cves:
            cve_ids = [cve_id for cve_id, _, _ in matching_cves]
            print(f"✅ {len(matching_cves)} 件のCVE番号を取得: {', '.join(cve_ids)}")
        else:
            print(f"⚠️ パッケージ '{package_name}' v{from_version}→v{to_version} に一致するCVEが見つかりません")

        return matching_cves

    except GithubException as e:
        print(f"⚠️ Dependabotアラート検索エラー (HTTP {e.status}): {e.data}")
        return []
    except Exception as e:
        print(f"⚠️ Dependabotアラート検索エラー: {e}")
        import traceback
        traceback.print_exc()
        return []


def get_previous_analysis(repo: str, pr_number: int, package_name: str, github_token: str) -> str:
    """同じPRの過去のvulnerability_analyzer.py生成コメントを取得

    Args:
        repo: リポジトリ名（owner/repo形式）
        pr_number: PR番号
        package_name: パッケージ名（そのパッケージに関するコメントのみを取得）
        github_token: GitHub トークン

    Returns:
        前回の分析結果（見つからない場合は空文字列）
    """
    try:
        g = Github(github_token)
        repository = g.get_repo(repo)
        pr = repository.get_pull(pr_number)
        comments = list(pr.get_issue_comments())

        # vulnerability_analyzer.pyによって生成されたコメントを探す
        for comment in reversed(comments):
            body = comment.body or ''
            if 'This comment was automatically generated by dependahunt.' in body:
                # マーカーからパッケージ情報を抽出
                version_info = markers.ANALYZED_PACKAGE.extract(body)

                if not version_info:
                    continue  # マーカーがないコメントはスキップ

                # パッケージ名が一致するかチェック
                if version_info.get('package') != package_name:
                    continue  # このパッケージのコメントではないのでスキップ

                # 詳細分析結果セクションを抽出
                # 結論部分と詳細分析部分を分離
                match = re.search(r'## 🔒 詳細分析結果.*?(?=## 📋 CVE基本情報|\Z)', body, re.DOTALL)
                if match:
                    return match.group(0).strip()

                # フォールバック: 全体を返す
                return body

        return ""

    except Exception as e:
        print(f"⚠️ 前回分析の取得に失敗: {e}")
        return ""


def post_github_comment(repo: str, pr_number: int, comment: str, github_token: str) -> bool:
    """GitHub APIを使ってPRにコメントを投稿"""
    try:
        g = Github(github_token)
        repository = g.get_repo(repo)
        pr = repository.get_pull(pr_number)
        created_comment = pr.create_issue_comment(comment)
        print(f"✅ コメントを投稿しました: {created_comment.html_url}")
        return True

    except GithubException as e:
        print(f"❌ GitHub APIエラー: {e}")
        return False
    except Exception as e:
        print(f"❌ コメント投稿エラー: {e}")
        return False
